name: Update README

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  readme-scribe:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: muesli/readme-scribe@master
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          template: _templates/README.md.tpl
          writeTo: README.md

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update generated README
          branch: dev-test
